exec-once = swww-daemon
# exec-once = swww img ~/Pictures/wallpaper.jpg
exec-once = swaync
exec-once = hyprpolkitagent

bind = $mod, D, exec, rofi -show drun
bind = $mod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy