# Ingat menit/detik terakhir saat aplikasi ditutup
save-position-on-quit=yes

# (Tambahan pintar) Kalau videonya ditutup saat udah bener-bener tamat, 
# memori posisinya nggak akan disimpan, jadi pas dibuka lagi langsung mulai dari awal
[eof-reached]
profile-cond=eof_reached
save-position-on-quit=no
# --- PENGATURAN WARNA & KUALITAS DEWA ---
profile=gpu-hq
video-output-levels=full
hwdec=auto-safe
